<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="2" total="3" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2018-08-12T15:02:59Z" name="Suite1" finished-at="2018-08-12T15:02:59Z" duration-ms="63">
    <groups>
      <group name="a">
        <method signature="IntroductionPageTest.validateIntroPageTitleTest()[pri:0, instance:com.gmail.qa.tests.IntroductionPageTest@2df3b89c]" name="validateIntroPageTitleTest" class="com.gmail.qa.tests.IntroductionPageTest"/>
      </group> <!-- a -->
    </groups>
    <test started-at="2018-08-12T15:02:59Z" name="Test1" finished-at="2018-08-12T15:02:59Z" duration-ms="31">
      <class name="com.gmail.qa.tests.IntroductionPageTest">
        <test-method signature="validateIntroPageTitleTest()[pri:0, instance:com.gmail.qa.tests.IntroductionPageTest@2df3b89c]" started-at="2018-08-12T15:02:59Z" name="validateIntroPageTitleTest" finished-at="2018-08-12T15:02:59Z" duration-ms="15" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at com.gmail.qa.tests.IntroductionPageTest.validateIntroPageTitleTest(IntroductionPageTest.java:34)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:383)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:344)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:417)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateIntroPageTitleTest -->
      </class> <!-- com.gmail.qa.tests.IntroductionPageTest -->
    </test> <!-- Test1 -->
    <test started-at="2018-08-12T15:02:59Z" name="Regression1" finished-at="2018-08-12T15:02:59Z" duration-ms="0">
    </test> <!-- Regression1 -->
  </suite> <!-- Suite1 -->
</testng-results>
